const {test,expect} = require('@playwright/test')
test('check google now',async({page})=>{
    await page.goto('https://www.google.com/search?q=parrot&tbm=isch')
    await page.waitForTimeout(1000)
    const firstImgChrome =page.locator('img[alt*="parrot" i]').first()
    await firstImgChrome.click()
    const previewParrot = page.locator('div[role="dialog"],div[role="main"]').locator( 'img[alt*="parrot" i]').first()
    await expect(previewParrot).toBeVisible()
    await expect(page).toHaveTitle(/parrot/i)
})