const {test,expect} = require('@playwright/test')
test.describe('Password Strength & Complexity Requirements',()=>{
    test('password shorter than 8 characters',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i}
        )
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('exampleshort1@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('Pass1!')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).not.toBe('')
    });
    test('Input a password with only lowercase letters',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i})
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('examplelower1@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('password123!')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).not.toBe('')
    });
    test('Input a password with only uppercase letters',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i})
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('exampleupper12@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('PASSWORD123!')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).not.toBe('')
    });
    test('Input a password without any numbers',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i})
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('example1@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('Password!')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).not.toBe('')
    });
    test('Input a password without any special characters',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i})
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('ex12454513@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('Password123')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).not.toBe('')
    });
    test('Input a password that meets all complexity criteria',async({page})=>{
        await page.goto('https://al-lubabah.vercel.app/auth')
        const registerPage = page.getByRole('button',{name:/create account|สร้างบัญชี/i})
        await registerPage.click()
        const emailBox = page.locator('input[type="email"]')
        await emailBox.fill('examplemeet@gmail.com')
        const pwdBox = page.locator('input[type="password"]')
        await pwdBox.fill('Secure@2026')
        const createBtn = page.locator('button[type="submit"]')
        await createBtn.click()
        const validateMessage =await pwdBox.evaluate(node=>node.validationMessage)
        await expect(validateMessage).toBe('')
    });
})