const { test, expect } = require('@playwright/test')
const { authPage } = require('../../constants/urls')
const validEmailPWd = require('../../test-data/valid-email-pattern-data.json')
test.describe.serial('Logout in Multi-tab Scenarios', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto(authPage)
        const { email, pwd } = validEmailPWd[0]
        await page.locator('input[type="email"]').fill(email)
        await page.locator('input[type="password"]').fill(pwd)
        await page.locator('button[type="submit"]').click()
        const invalidLogin = page.locator('span', { hasText: /Login Failed|فشل تسجيل الدخول|เข้าสู่ระบบไม่สำเร็จ/i })
        await expect(invalidLogin).not.toBeVisible()
    })
    test('Open the app in Tab A and Tab B; logout from Tab A, then refresh Tab B ', async ({ page, context }) => {
        const page2 = await context.newPage()
        const urlFirstPage = page.url()
        await page2.goto(urlFirstPage)
        await page.getByLabel('Settings').click()
        const signoutBtn = page.locator('button').getByText(/Sign Out|تسجيل الخروج|ออกจากระบบ/i)
        await signoutBtn.click()
        const logoutSuccessSign = page.getByRole('status').getByText(/ออกจากระบบแล้ว|Signed Out/i).first()
        await expect(logoutSuccessSign).toBeVisible()
        await expect(page).toHaveURL(authPage)
        await page2.reload()
        await expect(page2).toHaveURL(authPage)
        console.log(page2.url())
    })
    test('Logout from Tab A, then try to perform an action in Tab B', async ({ page, context }) => {
        await page.getByLabel('Settings').click()
        const page2 = await context.newPage()
        const pageUrl = page.url()
        await page2.goto(pageUrl)
        const signoutBtn = page.locator('button').getByText(/Sign Out|تسجيل الخروج|ออกจากระบบ/i)
        await signoutBtn.click()
        const logoutSuccessSign = page.getByRole('status').getByText(/ออกจากระบบแล้ว|Signed Out/i).first()
        await expect(logoutSuccessSign).toBeVisible()
        await expect(page).toHaveURL(authPage)
        const ramadanBtn = page2.getByLabel('Select language')
        await ramadanBtn.click()
        await expect(page2).toHaveURL(authPage)
    })
})